# Dictionary of gif urls used in cogs.deathroll

gifdict = {
    'start':    ['https://c.tenor.com/I7QkHH-wak4AAAAd/tenor.gif',
                 'https://c.tenor.com/aJLttNw5UlsAAAAd/tenor.gif',
                 'https://c.tenor.com/UHUrQzTj2PgAAAAd/tenor.gif',
                 'https://c.tenor.com/NKqSjU199eYAAAAd/tenor.gif',
                 'https://c.tenor.com/LywHByAmbkwAAAAd/tenor.gif',
                 'https://c.tenor.com/3vXSnnaDEpsAAAAd/tenor.gif',
                 'https://c.tenor.com/JiddDtSQKJwAAAAd/tenor.gif',
                 'https://c.tenor.com/MbxyaFe84VYAAAAd/tenor.gif'],
    'bigloss':  ['https://c.tenor.com/0YKj8P76e98AAAAd/tenor.gif',
                 'https://c.tenor.com/WvotbqtvuRUAAAAd/tenor.gif',
                 'https://c.tenor.com/mU8Le3LX3MEAAAAd/tenor.gif',
                 'https://c.tenor.com/chfOGBC51icAAAAd/tenor.gif',
                 'https://c.tenor.com/yxHvgtplhQUAAAAd/tenor.gif',
                 'https://static.klipy.com/ii/4e7bea9f7a3371424e6c16ebc93252fe/c0/56/vqj7vkCIa52alZlG.gif'],
    'highroll': ['https://c.tenor.com/y0pu4r01MXkAAAAd/tenor.gif',
                 'https://c.tenor.com/Ho6Eh52Aw50AAAAd/tenor.gif',
                 'https://c.tenor.com/RWmF33lS6_UAAAAd/tenor.gif',
                 'https://c.tenor.com/_5PCbIMFBCEAAAAd/tenor.gif',
                 'https://c.tenor.com/IxEoalvZM-AAAAAd/tenor.gif',
                 'https://c.tenor.com/yHWgY2PwamgAAAAd/tenor.gif'],
    'leet':     ['https://c.tenor.com/yt-NsmpTN54AAAAd/tenor.gif',
                 'https://c.tenor.com/IE_r1q13XpUAAAAd/tenor.gif',
                 'https://c.tenor.com/aMO9r7Pq19AAAAAd/tenor.gif'],
    '300':      ['https://c.tenor.com/ql7-Dp0nNL0AAAAC/tenor.gif'],
    '69':       ['https://c.tenor.com/GG9glZQxjBwAAAAd/tenor.gif',
                 'https://c.tenor.com/ZMMvXoBe8GwAAAAd/tenor.gif'],
    'loser':    ['https://c.tenor.com/RearbC1HzewAAAAd/tenor.gif',
                 'https://c.tenor.com/OUn0kZK9dB0AAAAd/tenor.gif',
                 'https://c.tenor.com/1fpEjOn5W3QAAAAd/tenor.gif',
                 'https://c.tenor.com/YMz2WAFV-GcAAAAd/tenor.gif',
                 'https://c.tenor.com/eTqdoJ96YP4AAAAd/tenor.gif',
                 'https://c.tenor.com/85iMZeffHQYAAAAC/tenor.gif',
                 'https://c.tenor.com/Eo_uafpjWDMAAAAC/tenor.gif',
                 'https://c.tenor.com/hduLb3FY_JMAAAAd/tenor.gif',
                 'https://c.tenor.com/1cd4rNbBLagAAAAd/tenor.gif',
                 'https://c.tenor.com/i14tqo0LZPIAAAAd/tenor.gif',
                 'https://c.tenor.com/5t7dwIkeSioAAAAd/tenor.gif',
                 'https://c.tenor.com/eFwAowaXPfMAAAAd/tenor.gif',
                 'https://c.tenor.com/BA0iIbcLm4AAAAAd/tenor.gif',
                 'https://static.klipy.com/ii/c3a19a0b747a76e98651f2b9a3cca5ff/b3/c1/guz6DK7B.gif'],
    'lowroll':  ['https://c.tenor.com/JbNlXxXl91QAAAAd/tenor.gif',
                 'https://c.tenor.com/aWUHvMsuYFkAAAAd/tenor.gif',
                 'https://c.tenor.com/e_vPwqBG5WUAAAAC/tenor.gif',
                 'https://c.tenor.com/djf8Lr3DdPwAAAAd/tenor.gif',
                 'https://c.tenor.com/Y-OZJ4OzBVAAAAAd/tenor.gif',
                 'https://c.tenor.com/FBsTPQt_59MAAAAd/tenor.gif'],
    'roll':     ['https://c.tenor.com/_f47EOhUYLQAAAAd/tenor.gif',
                 'https://c.tenor.com/InKwoemL4EAAAAAd/tenor.gif',
                 'https://c.tenor.com/5PepR8rD4U0AAAAd/tenor.gif',
                 'https://c.tenor.com/qeyYUP1MXJMAAAAd/tenor.gif',
                 'https://c.tenor.com/nVFR4jC3GZwAAAAd/tenor.gif',
                 'https://c.tenor.com/KzfDyYrsLngAAAAd/tenor.gif',
                 'https://c.tenor.com/05i-vUwsc20AAAAd/tenor.gif',
                 'https://c.tenor.com/VpQP6Yhbc8gAAAAd/tenor.gif',
                 'https://c.tenor.com/7adgNGXfyU0AAAAd/tenor.gif',
                 'https://c.tenor.com/Xw-tNXs79IoAAAAd/tenor.gif',
                 'https://c.tenor.com/K10_4tgaqhMAAAAd/tenor.gif',
                 'https://c.tenor.com/0GWfvb_IU5YAAAAd/tenor.gif',
                 'https://c.tenor.com/DT3lB0gNp_0AAAAd/tenor.gif',
                 'https://c.tenor.com/BEBPUCHsLRYAAAAd/tenor.gif',
                 'https://c.tenor.com/fgAa5IuzjPsAAAAd/tenor.gif',
                 'https://c.tenor.com/HcTPRPtGvIkAAAAd/tenor.gif',
                 'https://c.tenor.com/q4E9apwG6aMAAAAd/tenor.gif',
                 'https://c.tenor.com/aAnAtTZkfrEAAAAd/tenor.gif',
                 'https://static.klipy.com/ii/c3a19a0b747a76e98651f2b9a3cca5ff/6c/67/GILjpYlK.gif',
                 'https://static.klipy.com/ii/c3a19a0b747a76e98651f2b9a3cca5ff/a1/fd/IcfgAHkU.gif',
                 'https://static.klipy.com/ii/d7aec6f6f171607374b2065c836f92f4/a2/be/j3q340xW.gif'],
    'whew':     ['https://c.tenor.com/OsBUnbQbfsEAAAAC/tenor.gif',
                 'https://c.tenor.com/8gE5vCt_XIoAAAAC/tenor.gif',
                 'https://c.tenor.com/Li11L5d4GakAAAAC/tenor.gif',
                 'https://c.tenor.com/D4TuNIn61aEAAAAd/tenor.gif',
                 'https://c.tenor.com/NqhZNESuzusAAAAC/tenor.gif',
                 'https://c.tenor.com/2uHmVoZGMecAAAAd/tenor.gif',
                 'https://c.tenor.com/FTxtRehmCc4AAAAd/tenor.gif',
                 'https://c.tenor.com/87QKarbzVisAAAAd/tenor.gif',
                 'https://c.tenor.com/g_d3iHyzc68AAAAd/tenor.gif',
                 'https://c.tenor.com/_vTVykiMmKMAAAAd/tenor.gif',
                 'https://static.klipy.com/ii/2711dd8a75a85be822d136ec94899b3f/7e/8e/wZLzRxtV.gif',
                 'https://static.klipy.com/ii/4e7bea9f7a3371424e6c16ebc93252fe/6d/e3/KqwhlUSHAONxEd.gif'],
    'winner':   ['https://c.tenor.com/Zx4EYt-kXmMAAAAd/tenor.gif',
                 'https://c.tenor.com/nwY77jVH52oAAAAC/tenor.gif',
                 'https://c.tenor.com/MTGiVk7eL9gAAAAC/tenor.gif',
                 'https://c.tenor.com/Z2HxUamVZTMAAAAd/tenor.gif',
                 'https://c.tenor.com/9mUqamN2SOIAAAAC/tenor.gif',
                 'https://c.tenor.com/xlhV0tC8tMUAAAAd/tenor.gif',
                 'https://c.tenor.com/1WQApj0YBeUAAAAd/tenor.gif',
                 'https://c.tenor.com/UPW1-calBtQAAAAC/tenor.gif',
                 'https://c.tenor.com/YA9gJF0gkiQAAAAd/tenor.gif',
                 'https://c.tenor.com/iycut67L9eUAAAAd/tenor.gif',
                 'https://c.tenor.com/ogEmYGu9T4EAAAAC/tenor.gif',
                 'https://c.tenor.com/1S-TYzX6HPwAAAAd/tenor.gif',
                 'https://c.tenor.com/FCtDCj3ihF8AAAAd/tenor.gif',
                 'https://c.tenor.com/VfBGHQrPHOsAAAAd/tenor.gif',
                 'https://c.tenor.com/w6NNS1UO3aIAAAAd/tenor.gif',
                 'https://c.tenor.com/N342b6qb0soAAAAd/tenor.gif',
                 'https://c.tenor.com/XEPLVNSYtIAAAAAd/tenor.gif',
                 'https://c.tenor.com/4HB6Vl3KgYEAAAAd/tenor.gif']
}
